language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.3.7
  # - 2.1.3
  # - 2.0

before_install:
    - sudo apt install ruby-bundler
    # - sudo snap install ruby
    - bundle install --path vendor/bundle

script:
    - bundle exec rake spec
